### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS SHOW
GET http://localhost:3000/products/1.json

### PRODUCTS CREATE HARD-CODED
# POST http://localhost:3000/products.json

### PRODUCT CREATE NON HARD-CODED
POST http://localhost:3000/products.json
Content-Type: application/json

  {
  "name": "Wax Seal",
  "price": 1.99,
  "description": "TEST",
  "inventory": "2",
  "supplier_id": 2
  }

### PRODUCT UPDATE
PATCH http://localhost:3000/products/8.json
Content-Type: application/json

  {
  "name": "Wax Seal",
  "price": 15.95,
  "description": "A seal.",
  "supplier_id": 2
  }

### PRODUCT DESTROY
DELETE http://localhost:3000/products/6.json

### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

  {
  "name": "Test Name",
  "email": "test@name.com",
  "password": "password",
  "password_confirmation": "password"
  }

### SESSIONS CREATE (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

  {
  "email": "test@name.com",
  "password": "password"
  }
