### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS SHOW
GET http://localhost:3000/products/1.json

### PRODUCTS CREATE HARD-CODED
# POST http://localhost:3000/products.json

### PRODUCT CREATE NON HARD-CODED
POST http://localhost:3000/products.json
Content-Type: application/json

  {
  "name": "Wax Seal",
  "price": 1.99,
  "description": "TEST",
  "inventory": "2",
  "supplier_id": 2
  }

### PRODUCT UPDATE
PATCH http://localhost:3000/products/8.json
Content-Type: application/json

  {
  "name": "Wax Seal",
  "price": 15.95,
  "description": "A seal.",
  "supplier_id": 2
  }

### PRODUCT DESTROY
DELETE http://localhost:3000/products/6.json

### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

  {
  "name": "Test Name",
  "email": "test@name.com",
  "password": "password",
  "password_confirmation": "password"
  }

### SESSIONS CREATE (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgxOTI0Njh9.yGFHO_qe4wFp29suT5JH3P2_73Bwu318Gg-VDgwMR3Q

  {
  "email": "test@name.com",
  "password": "password"
  }

### ORDERS CREATE
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgxOTI0Njh9.yGFHO_qe4wFp29suT5JH3P2_73Bwu318Gg-VDgwMR3Q

  {
  "user_id": 1,
  "product_id": 1,
  "quantity": 1,
  "subtotal": 6, 
  "tax": 2,
  "total": 12
  }

### ORDERS SHOW
GET http://localhost:3000/orders/1.json

### ORDERS INDEX
GET http://localhost:3000/orders.json