### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS SHOW
GET http://localhost:3000/products/1.json

### PRODUCTS CREATE HARD-CODED
# POST http://localhost:3000/products.json


### PRODUCT CREATE NON HARD-CODED
POST http://localhost:3000/products.json
Content-Type: application/json

  {
  "name": "Wax Seal",
  "price": 1.99,
  "image_url": "TEST",
  "description": "TEST",
  "inventory": "2"
  }

### PRODUCT UPDATE
PATCH http://localhost:3000/products/8.json
Content-Type: application/json

  {
  "name": "Wax Seal",
  "price": 15.95,
  "image_url": "TEST",
  "description": "A seal."
  }

### PRODUCT DESTROY
DELETE http://localhost:3000/products/6.json